'use strict';
// Generate Home Assistant `mqtt:` YAML entities for the spa.
//
// This HA instance has never had MQTT auto-discovery working, so entities are
// declared explicitly. Generating them keeps the topics identical to what the
// gateway and simulator actually publish — hand-maintaining 40 blocks drifts.
//
//   node gen-ha-yaml.js real > spa-real.yaml
//   node gen-ha-yaml.js sim  > spa-sim.yaml
//
// Paste the output into the existing `mqtt:` list in configuration.yaml.

const TARGETS = {
  real: { prefix: 'spa',     id: 'balboa_spa',     label: 'Spa',     devName: 'Balboa Spa' },
  sim:  { prefix: 'spa-sim', id: 'balboa_spa_sim', label: 'Spa Sim', devName: 'Balboa Spa (Simulated)' },
};

const which = process.argv[2] || 'real';
const T = TARGETS[which];
if (!T) { console.error(`usage: gen-ha-yaml.js [real|sim]`); process.exit(1); }

const { prefix: P, id: ID, label: L, devName } = T;

const dev = (ind) => {
  const p = ' '.repeat(ind);
  return [
    `${p}device:`,
    `${p}  identifiers: "${ID}"`,
    `${p}  name: "${devName}"`,
    `${p}  manufacturer: "Balboa Water Group"`,
    `${p}  model: "CNBP501X"`,
  ].join('\n');
};

const avail = (ind) => {
  const p = ' '.repeat(ind);
  return [
    `${p}availability:`,
    `${p}  - topic: "${P}/status"`,
    `${p}    payload_available: "online"`,
    `${p}    payload_not_available: "offline"`,
  ].join('\n');
};

const out = [];
const push = (s) => out.push(s);

push(`# ---------------------------------------------------------------------------`);
push(`# ${devName} — generated by ha/gen-ha-yaml.js (${which}). Do not hand-edit;`);
push(`# regenerate if topics change. Paste into the mqtt: list in configuration.yaml.`);
push(`# All temperatures on the wire are CELSIUS.`);
push(`# ---------------------------------------------------------------------------`);

// --- climate ---
push(`  - climate:
      name: "${L}"
      unique_id: ${ID}_climate
      modes: ["off", "heat"]
      mode_state_topic: "${P}/climate/spa/mode/state"
      mode_command_topic: "${P}/climate/spa/mode/command"
      current_temperature_topic: "${P}/climate/spa/current_temperature/state"
      temperature_state_topic: "${P}/climate/spa/target_temperature/state"
      temperature_command_topic: "${P}/climate/spa/target_temperature/command"
      action_topic: "${P}/climate/spa/action/state"
      min_temp: 10
      max_temp: 40
      temp_step: 0.5
      temperature_unit: C
      precision: 0.1
      retain: false
${avail(6)}
${dev(6)}`);

// --- fan: jets. HA maps percentage onto the 1..2 speed range. ---
push(`  - fan:
      name: "${L} Jets"
      unique_id: ${ID}_jets
      state_topic: "${P}/fan/spa_jets/state"
      command_topic: "${P}/fan/spa_jets/command"
      percentage_state_topic: "${P}/fan/spa_jets/speed_level/state"
      percentage_command_topic: "${P}/fan/spa_jets/speed_level/command"
      speed_range_min: 1
      speed_range_max: 2
      payload_on: "ON"
      payload_off: "OFF"
      retain: false
${avail(6)}
${dev(6)}`);

// --- switches ---
for (const [obj, name] of [['spa_light', 'Light'], ['spa_hold', 'Hold']]) {
  push(`  - switch:
      name: "${L} ${name}"
      unique_id: ${ID}_${obj}
      state_topic: "${P}/switch/${obj}/state"
      command_topic: "${P}/switch/${obj}/command"
      payload_on: "ON"
      payload_off: "OFF"
      state_on: "ON"
      state_off: "OFF"
      optimistic: false
      retain: false
${avail(6)}
${dev(6)}`);
}

// --- selects ---
for (const [obj, name, opts] of [
  ['spa_heating_mode', 'Heating Mode', ['ready', 'rest']],
  ['spa_temperature_range', 'Temperature Range', ['high', 'low']],
  ['spa_temperature_scale', 'Temperature Scale', ['fahrenheit', 'celsius']],
]) {
  push(`  - select:
      name: "${L} ${name}"
      unique_id: ${ID}_${obj}
      state_topic: "${P}/select/${obj}/state"
      command_topic: "${P}/select/${obj}/command"
      options: [${opts.map((o) => `"${o}"`).join(', ')}]
      retain: false
${avail(6)}
${dev(6)}`);
}

// --- temperature sensors (Celsius on the wire) ---
for (const [obj, name] of [
  ['spa_current_temperature', 'Current Temperature'],
  ['spa_target_temperature', 'Target Temperature'],
]) {
  push(`  - sensor:
      name: "${L} ${name}"
      unique_id: ${ID}_${obj}
      state_topic: "${P}/sensor/${obj}/state"
      unit_of_measurement: "°C"
      device_class: temperature
      state_class: measurement
      suggested_display_precision: 1
${avail(6)}
${dev(6)}`);
}

// --- text sensors. NOTE: published under the `sensor` component, not text_sensor. ---
for (const [obj, name] of [
  ['spa_model', 'Model'],
  ['spa_firmware_version', 'Firmware Version'],
  ['spa_notification', 'Notification'],
]) {
  push(`  - sensor:
      name: "${L} ${name}"
      unique_id: ${ID}_${obj}
      state_topic: "${P}/sensor/${obj}/state"
${avail(6)}
${dev(6)}`);
}

// --- binary sensors ---
for (const [obj, name, cls] of [
  ['spa_heating', 'Heating', 'heat'],
  ['spa_priming', 'Priming', null],
  ['spa_filter_cycle_1_running', 'Filter Cycle 1 Running', 'running'],
  ['spa_circulation_pump', 'Circulation Pump', 'running'],
  ['spa_bus_connected', 'Bus Connected', 'connectivity'],
]) {
  push(`  - binary_sensor:
      name: "${L} ${name}"
      unique_id: ${ID}_${obj}
      state_topic: "${P}/binary_sensor/${obj}/state"
      payload_on: "ON"
      payload_off: "OFF"${cls ? `\n      device_class: ${cls}` : ''}
${avail(6)}
${dev(6)}`);
}

// --- numbers ---
for (const [obj, name, min, max, step, unit] of [
  ['spa_filter_1_start_hour', 'Filter 1 Start Hour', 0, 23, 1, 'h'],
  ['spa_filter_1_duration', 'Filter 1 Duration', 0, 1440, 15, 'min'],
]) {
  push(`  - number:
      name: "${L} ${name}"
      unique_id: ${ID}_${obj}
      state_topic: "${P}/number/${obj}/state"
      command_topic: "${P}/number/${obj}/command"
      min: ${min}
      max: ${max}
      step: ${step}
      unit_of_measurement: "${unit}"
      mode: box
      retain: false
${avail(6)}
${dev(6)}`);
}

// --- buttons ---
for (const [obj, name] of [
  ['spa_clear_notification', 'Clear Notification'],
  ['spa_normal_operation', 'Normal Operation'],
]) {
  push(`  - button:
      name: "${L} ${name}"
      unique_id: ${ID}_${obj}
      command_topic: "${P}/button/${obj}/command"
      payload_press: "PRESS"
      retain: false
${avail(6)}
${dev(6)}`);
}

console.log(out.join('\n\n'));
